image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - chmod +x gradlew

build_script:
  - ./gradlew clean build

before_test:
  - docker-compose up -d
  - java -jar ./artifacts/aqa-shop.jar &

test_script:
  # Подождем, пока контейнеры поднимутся
  - sleep 10
  - ./gradlew test
  
# Завершаем работу контейнеров после тестов
after_test:
  - docker-compose down
